# Generated by Django 2.1 on 2018-11-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_image1', models.ImageField(upload_to='')),
                ('product_image2', models.ImageField(upload_to='')),
                ('product_image3', models.ImageField(upload_to='')),
                ('product_image4', models.ImageField(upload_to='')),
                ('product_image5', models.ImageField(upload_to='')),
                ('product_specs', models.TextField(max_length=1000)),
                ('product_sellerName', models.CharField(max_length=200)),
                ('product_sellerAddress', models.CharField(max_length=300)),
                ('product_sellerPhoneNo', models.CharField(max_length=13)),
                ('product_sellerID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(max_length=200)),
                ('subCategory_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.SubCategory'),
        ),
    ]
