# Generated by Django 2.1 on 2018-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_sizes',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_sellerID',
            field=models.PositiveIntegerField(),
        ),
    ]
