# Generated by Django 2.1 on 2018-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_products_product_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
