# Generated by Django 2.1 on 2018-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_products_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_specs',
            field=models.TextField(max_length=8000),
        ),
    ]
