# Generated by Django 2.1 on 2018-11-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20181106_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_sizes',
        ),
    ]
